#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#index:
#    path: /
#    controller: App\Controller\ArticleController::homepage

#movie_index:
#  path:       /movies/{page}
#  controller: App\Controller\MovieApiController::index
#  defaults:
#    page: 1
#  requirements:
#    page: '\d+'